/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedManageSolicitationsRouteImport } from './routes/_authenticated/manage/solicitations'
import { Route as AuthenticatedManageMembersRouteImport } from './routes/_authenticated/manage/members'
import { Route as AuthenticatedManageLocationsRouteImport } from './routes/_authenticated/manage/locations'
import { Route as AuthenticatedManageEventsRouteImport } from './routes/_authenticated/manage/events'
import { Route as AuthenticatedManageAccountsRouteImport } from './routes/_authenticated/manage/accounts'
import { Route as AuthenticatedManageMembersMemberIdRouteImport } from './routes/_authenticated/manage/members/$memberId'
import { Route as AuthenticatedManageLocationsLocationIdRouteImport } from './routes/_authenticated/manage/locations/$locationId'
import { Route as AuthenticatedManageEventsEventIdRouteImport } from './routes/_authenticated/manage/events/$eventId'

const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManageSolicitationsRoute =
  AuthenticatedManageSolicitationsRouteImport.update({
    id: '/manage/solicitations',
    path: '/manage/solicitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageMembersRoute =
  AuthenticatedManageMembersRouteImport.update({
    id: '/manage/members',
    path: '/manage/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageLocationsRoute =
  AuthenticatedManageLocationsRouteImport.update({
    id: '/manage/locations',
    path: '/manage/locations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageEventsRoute =
  AuthenticatedManageEventsRouteImport.update({
    id: '/manage/events',
    path: '/manage/events',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageAccountsRoute =
  AuthenticatedManageAccountsRouteImport.update({
    id: '/manage/accounts',
    path: '/manage/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageMembersMemberIdRoute =
  AuthenticatedManageMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedManageMembersRoute,
  } as any)
const AuthenticatedManageLocationsLocationIdRoute =
  AuthenticatedManageLocationsLocationIdRouteImport.update({
    id: '/$locationId',
    path: '/$locationId',
    getParentRoute: () => AuthenticatedManageLocationsRoute,
  } as any)
const AuthenticatedManageEventsEventIdRoute =
  AuthenticatedManageEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedManageEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manage': typeof ManageRoute
  '/home': typeof AuthenticatedHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/manage/accounts': typeof AuthenticatedManageAccountsRoute
  '/manage/events': typeof AuthenticatedManageEventsRouteWithChildren
  '/manage/locations': typeof AuthenticatedManageLocationsRouteWithChildren
  '/manage/members': typeof AuthenticatedManageMembersRouteWithChildren
  '/manage/solicitations': typeof AuthenticatedManageSolicitationsRoute
  '/manage/events/$eventId': typeof AuthenticatedManageEventsEventIdRoute
  '/manage/locations/$locationId': typeof AuthenticatedManageLocationsLocationIdRoute
  '/manage/members/$memberId': typeof AuthenticatedManageMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manage': typeof ManageRoute
  '/home': typeof AuthenticatedHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/manage/accounts': typeof AuthenticatedManageAccountsRoute
  '/manage/events': typeof AuthenticatedManageEventsRouteWithChildren
  '/manage/locations': typeof AuthenticatedManageLocationsRouteWithChildren
  '/manage/members': typeof AuthenticatedManageMembersRouteWithChildren
  '/manage/solicitations': typeof AuthenticatedManageSolicitationsRoute
  '/manage/events/$eventId': typeof AuthenticatedManageEventsEventIdRoute
  '/manage/locations/$locationId': typeof AuthenticatedManageLocationsLocationIdRoute
  '/manage/members/$memberId': typeof AuthenticatedManageMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/manage': typeof ManageRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/manage/accounts': typeof AuthenticatedManageAccountsRoute
  '/_authenticated/manage/events': typeof AuthenticatedManageEventsRouteWithChildren
  '/_authenticated/manage/locations': typeof AuthenticatedManageLocationsRouteWithChildren
  '/_authenticated/manage/members': typeof AuthenticatedManageMembersRouteWithChildren
  '/_authenticated/manage/solicitations': typeof AuthenticatedManageSolicitationsRoute
  '/_authenticated/manage/events/$eventId': typeof AuthenticatedManageEventsEventIdRoute
  '/_authenticated/manage/locations/$locationId': typeof AuthenticatedManageLocationsLocationIdRoute
  '/_authenticated/manage/members/$memberId': typeof AuthenticatedManageMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manage'
    | '/home'
    | '/auth/login'
    | '/auth/register'
    | '/manage/accounts'
    | '/manage/events'
    | '/manage/locations'
    | '/manage/members'
    | '/manage/solicitations'
    | '/manage/events/$eventId'
    | '/manage/locations/$locationId'
    | '/manage/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manage'
    | '/home'
    | '/auth/login'
    | '/auth/register'
    | '/manage/accounts'
    | '/manage/events'
    | '/manage/locations'
    | '/manage/members'
    | '/manage/solicitations'
    | '/manage/events/$eventId'
    | '/manage/locations/$locationId'
    | '/manage/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/manage'
    | '/_authenticated/home'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/manage/accounts'
    | '/_authenticated/manage/events'
    | '/_authenticated/manage/locations'
    | '/_authenticated/manage/members'
    | '/_authenticated/manage/solicitations'
    | '/_authenticated/manage/events/$eventId'
    | '/_authenticated/manage/locations/$locationId'
    | '/_authenticated/manage/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ManageRoute: typeof ManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/solicitations': {
      id: '/_authenticated/manage/solicitations'
      path: '/manage/solicitations'
      fullPath: '/manage/solicitations'
      preLoaderRoute: typeof AuthenticatedManageSolicitationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/members': {
      id: '/_authenticated/manage/members'
      path: '/manage/members'
      fullPath: '/manage/members'
      preLoaderRoute: typeof AuthenticatedManageMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/locations': {
      id: '/_authenticated/manage/locations'
      path: '/manage/locations'
      fullPath: '/manage/locations'
      preLoaderRoute: typeof AuthenticatedManageLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/events': {
      id: '/_authenticated/manage/events'
      path: '/manage/events'
      fullPath: '/manage/events'
      preLoaderRoute: typeof AuthenticatedManageEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/accounts': {
      id: '/_authenticated/manage/accounts'
      path: '/manage/accounts'
      fullPath: '/manage/accounts'
      preLoaderRoute: typeof AuthenticatedManageAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/members/$memberId': {
      id: '/_authenticated/manage/members/$memberId'
      path: '/$memberId'
      fullPath: '/manage/members/$memberId'
      preLoaderRoute: typeof AuthenticatedManageMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedManageMembersRoute
    }
    '/_authenticated/manage/locations/$locationId': {
      id: '/_authenticated/manage/locations/$locationId'
      path: '/$locationId'
      fullPath: '/manage/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedManageLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedManageLocationsRoute
    }
    '/_authenticated/manage/events/$eventId': {
      id: '/_authenticated/manage/events/$eventId'
      path: '/$eventId'
      fullPath: '/manage/events/$eventId'
      preLoaderRoute: typeof AuthenticatedManageEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedManageEventsRoute
    }
  }
}

interface AuthenticatedManageEventsRouteChildren {
  AuthenticatedManageEventsEventIdRoute: typeof AuthenticatedManageEventsEventIdRoute
}

const AuthenticatedManageEventsRouteChildren: AuthenticatedManageEventsRouteChildren =
  {
    AuthenticatedManageEventsEventIdRoute:
      AuthenticatedManageEventsEventIdRoute,
  }

const AuthenticatedManageEventsRouteWithChildren =
  AuthenticatedManageEventsRoute._addFileChildren(
    AuthenticatedManageEventsRouteChildren,
  )

interface AuthenticatedManageLocationsRouteChildren {
  AuthenticatedManageLocationsLocationIdRoute: typeof AuthenticatedManageLocationsLocationIdRoute
}

const AuthenticatedManageLocationsRouteChildren: AuthenticatedManageLocationsRouteChildren =
  {
    AuthenticatedManageLocationsLocationIdRoute:
      AuthenticatedManageLocationsLocationIdRoute,
  }

const AuthenticatedManageLocationsRouteWithChildren =
  AuthenticatedManageLocationsRoute._addFileChildren(
    AuthenticatedManageLocationsRouteChildren,
  )

interface AuthenticatedManageMembersRouteChildren {
  AuthenticatedManageMembersMemberIdRoute: typeof AuthenticatedManageMembersMemberIdRoute
}

const AuthenticatedManageMembersRouteChildren: AuthenticatedManageMembersRouteChildren =
  {
    AuthenticatedManageMembersMemberIdRoute:
      AuthenticatedManageMembersMemberIdRoute,
  }

const AuthenticatedManageMembersRouteWithChildren =
  AuthenticatedManageMembersRoute._addFileChildren(
    AuthenticatedManageMembersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedManageAccountsRoute: typeof AuthenticatedManageAccountsRoute
  AuthenticatedManageEventsRoute: typeof AuthenticatedManageEventsRouteWithChildren
  AuthenticatedManageLocationsRoute: typeof AuthenticatedManageLocationsRouteWithChildren
  AuthenticatedManageMembersRoute: typeof AuthenticatedManageMembersRouteWithChildren
  AuthenticatedManageSolicitationsRoute: typeof AuthenticatedManageSolicitationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedManageAccountsRoute: AuthenticatedManageAccountsRoute,
  AuthenticatedManageEventsRoute: AuthenticatedManageEventsRouteWithChildren,
  AuthenticatedManageLocationsRoute:
    AuthenticatedManageLocationsRouteWithChildren,
  AuthenticatedManageMembersRoute: AuthenticatedManageMembersRouteWithChildren,
  AuthenticatedManageSolicitationsRoute: AuthenticatedManageSolicitationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ManageRoute: ManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
