/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedManageSolicitationsRouteImport } from './routes/_authenticated/manage/solicitations'
import { Route as AuthenticatedManageOratoriosRouteImport } from './routes/_authenticated/manage/oratorios'
import { Route as AuthenticatedManageMembersRouteImport } from './routes/_authenticated/manage/members'
import { Route as AuthenticatedManageLocationsRouteImport } from './routes/_authenticated/manage/locations'
import { Route as AuthenticatedManageEventsRouteImport } from './routes/_authenticated/manage/events'
import { Route as AuthenticatedManageAccountsRouteImport } from './routes/_authenticated/manage/accounts'
import { Route as AuthenticatedManageOratoriosIndexRouteImport } from './routes/_authenticated/manage/oratorios.index'
import { Route as AuthenticatedManageOratoriosOratorianosRouteImport } from './routes/_authenticated/manage/oratorios.oratorianos'
import { Route as AuthenticatedManageOratoriosOratorioIdRouteImport } from './routes/_authenticated/manage/oratorios.$oratorioId'
import { Route as AuthenticatedManageMembersMemberIdRouteImport } from './routes/_authenticated/manage/members/$memberId'
import { Route as AuthenticatedManageEventsEventIdRouteImport } from './routes/_authenticated/manage/events_.$eventId'
import { Route as AuthenticatedManageOratoriosOratorianosOratorianoIdRouteImport } from './routes/_authenticated/manage/oratorios.oratorianos_.$oratorianoId'
import { Route as AuthenticatedManageOratoriosOratorioIdAttendanceRouteImport } from './routes/_authenticated/manage/oratorios.$oratorioId_.attendance'

const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManageSolicitationsRoute =
  AuthenticatedManageSolicitationsRouteImport.update({
    id: '/manage/solicitations',
    path: '/manage/solicitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageOratoriosRoute =
  AuthenticatedManageOratoriosRouteImport.update({
    id: '/manage/oratorios',
    path: '/manage/oratorios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageMembersRoute =
  AuthenticatedManageMembersRouteImport.update({
    id: '/manage/members',
    path: '/manage/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageLocationsRoute =
  AuthenticatedManageLocationsRouteImport.update({
    id: '/manage/locations',
    path: '/manage/locations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageEventsRoute =
  AuthenticatedManageEventsRouteImport.update({
    id: '/manage/events',
    path: '/manage/events',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageAccountsRoute =
  AuthenticatedManageAccountsRouteImport.update({
    id: '/manage/accounts',
    path: '/manage/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageOratoriosIndexRoute =
  AuthenticatedManageOratoriosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManageOratoriosRoute,
  } as any)
const AuthenticatedManageOratoriosOratorianosRoute =
  AuthenticatedManageOratoriosOratorianosRouteImport.update({
    id: '/oratorianos',
    path: '/oratorianos',
    getParentRoute: () => AuthenticatedManageOratoriosRoute,
  } as any)
const AuthenticatedManageOratoriosOratorioIdRoute =
  AuthenticatedManageOratoriosOratorioIdRouteImport.update({
    id: '/$oratorioId',
    path: '/$oratorioId',
    getParentRoute: () => AuthenticatedManageOratoriosRoute,
  } as any)
const AuthenticatedManageMembersMemberIdRoute =
  AuthenticatedManageMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedManageMembersRoute,
  } as any)
const AuthenticatedManageEventsEventIdRoute =
  AuthenticatedManageEventsEventIdRouteImport.update({
    id: '/manage/events_/$eventId',
    path: '/manage/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManageOratoriosOratorianosOratorianoIdRoute =
  AuthenticatedManageOratoriosOratorianosOratorianoIdRouteImport.update({
    id: '/oratorianos_/$oratorianoId',
    path: '/oratorianos/$oratorianoId',
    getParentRoute: () => AuthenticatedManageOratoriosRoute,
  } as any)
const AuthenticatedManageOratoriosOratorioIdAttendanceRoute =
  AuthenticatedManageOratoriosOratorioIdAttendanceRouteImport.update({
    id: '/$oratorioId_/attendance',
    path: '/$oratorioId/attendance',
    getParentRoute: () => AuthenticatedManageOratoriosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manage': typeof ManageRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/manage/accounts': typeof AuthenticatedManageAccountsRoute
  '/manage/events': typeof AuthenticatedManageEventsRoute
  '/manage/locations': typeof AuthenticatedManageLocationsRoute
  '/manage/members': typeof AuthenticatedManageMembersRouteWithChildren
  '/manage/oratorios': typeof AuthenticatedManageOratoriosRouteWithChildren
  '/manage/solicitations': typeof AuthenticatedManageSolicitationsRoute
  '/manage/events/$eventId': typeof AuthenticatedManageEventsEventIdRoute
  '/manage/members/$memberId': typeof AuthenticatedManageMembersMemberIdRoute
  '/manage/oratorios/$oratorioId': typeof AuthenticatedManageOratoriosOratorioIdRoute
  '/manage/oratorios/oratorianos': typeof AuthenticatedManageOratoriosOratorianosRoute
  '/manage/oratorios/': typeof AuthenticatedManageOratoriosIndexRoute
  '/manage/oratorios/$oratorioId/attendance': typeof AuthenticatedManageOratoriosOratorioIdAttendanceRoute
  '/manage/oratorios/oratorianos/$oratorianoId': typeof AuthenticatedManageOratoriosOratorianosOratorianoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manage': typeof ManageRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/manage/accounts': typeof AuthenticatedManageAccountsRoute
  '/manage/events': typeof AuthenticatedManageEventsRoute
  '/manage/locations': typeof AuthenticatedManageLocationsRoute
  '/manage/members': typeof AuthenticatedManageMembersRouteWithChildren
  '/manage/solicitations': typeof AuthenticatedManageSolicitationsRoute
  '/manage/events/$eventId': typeof AuthenticatedManageEventsEventIdRoute
  '/manage/members/$memberId': typeof AuthenticatedManageMembersMemberIdRoute
  '/manage/oratorios/$oratorioId': typeof AuthenticatedManageOratoriosOratorioIdRoute
  '/manage/oratorios/oratorianos': typeof AuthenticatedManageOratoriosOratorianosRoute
  '/manage/oratorios': typeof AuthenticatedManageOratoriosIndexRoute
  '/manage/oratorios/$oratorioId/attendance': typeof AuthenticatedManageOratoriosOratorioIdAttendanceRoute
  '/manage/oratorios/oratorianos/$oratorianoId': typeof AuthenticatedManageOratoriosOratorianosOratorianoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/manage': typeof ManageRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/manage/accounts': typeof AuthenticatedManageAccountsRoute
  '/_authenticated/manage/events': typeof AuthenticatedManageEventsRoute
  '/_authenticated/manage/locations': typeof AuthenticatedManageLocationsRoute
  '/_authenticated/manage/members': typeof AuthenticatedManageMembersRouteWithChildren
  '/_authenticated/manage/oratorios': typeof AuthenticatedManageOratoriosRouteWithChildren
  '/_authenticated/manage/solicitations': typeof AuthenticatedManageSolicitationsRoute
  '/_authenticated/manage/events_/$eventId': typeof AuthenticatedManageEventsEventIdRoute
  '/_authenticated/manage/members/$memberId': typeof AuthenticatedManageMembersMemberIdRoute
  '/_authenticated/manage/oratorios/$oratorioId': typeof AuthenticatedManageOratoriosOratorioIdRoute
  '/_authenticated/manage/oratorios/oratorianos': typeof AuthenticatedManageOratoriosOratorianosRoute
  '/_authenticated/manage/oratorios/': typeof AuthenticatedManageOratoriosIndexRoute
  '/_authenticated/manage/oratorios/$oratorioId_/attendance': typeof AuthenticatedManageOratoriosOratorioIdAttendanceRoute
  '/_authenticated/manage/oratorios/oratorianos_/$oratorianoId': typeof AuthenticatedManageOratoriosOratorianosOratorianoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manage'
    | '/home'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/manage/accounts'
    | '/manage/events'
    | '/manage/locations'
    | '/manage/members'
    | '/manage/oratorios'
    | '/manage/solicitations'
    | '/manage/events/$eventId'
    | '/manage/members/$memberId'
    | '/manage/oratorios/$oratorioId'
    | '/manage/oratorios/oratorianos'
    | '/manage/oratorios/'
    | '/manage/oratorios/$oratorioId/attendance'
    | '/manage/oratorios/oratorianos/$oratorianoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manage'
    | '/home'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/manage/accounts'
    | '/manage/events'
    | '/manage/locations'
    | '/manage/members'
    | '/manage/solicitations'
    | '/manage/events/$eventId'
    | '/manage/members/$memberId'
    | '/manage/oratorios/$oratorioId'
    | '/manage/oratorios/oratorianos'
    | '/manage/oratorios'
    | '/manage/oratorios/$oratorioId/attendance'
    | '/manage/oratorios/oratorianos/$oratorianoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/manage'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/manage/accounts'
    | '/_authenticated/manage/events'
    | '/_authenticated/manage/locations'
    | '/_authenticated/manage/members'
    | '/_authenticated/manage/oratorios'
    | '/_authenticated/manage/solicitations'
    | '/_authenticated/manage/events_/$eventId'
    | '/_authenticated/manage/members/$memberId'
    | '/_authenticated/manage/oratorios/$oratorioId'
    | '/_authenticated/manage/oratorios/oratorianos'
    | '/_authenticated/manage/oratorios/'
    | '/_authenticated/manage/oratorios/$oratorioId_/attendance'
    | '/_authenticated/manage/oratorios/oratorianos_/$oratorianoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ManageRoute: typeof ManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/solicitations': {
      id: '/_authenticated/manage/solicitations'
      path: '/manage/solicitations'
      fullPath: '/manage/solicitations'
      preLoaderRoute: typeof AuthenticatedManageSolicitationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/oratorios': {
      id: '/_authenticated/manage/oratorios'
      path: '/manage/oratorios'
      fullPath: '/manage/oratorios'
      preLoaderRoute: typeof AuthenticatedManageOratoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/members': {
      id: '/_authenticated/manage/members'
      path: '/manage/members'
      fullPath: '/manage/members'
      preLoaderRoute: typeof AuthenticatedManageMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/locations': {
      id: '/_authenticated/manage/locations'
      path: '/manage/locations'
      fullPath: '/manage/locations'
      preLoaderRoute: typeof AuthenticatedManageLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/events': {
      id: '/_authenticated/manage/events'
      path: '/manage/events'
      fullPath: '/manage/events'
      preLoaderRoute: typeof AuthenticatedManageEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/accounts': {
      id: '/_authenticated/manage/accounts'
      path: '/manage/accounts'
      fullPath: '/manage/accounts'
      preLoaderRoute: typeof AuthenticatedManageAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/oratorios/': {
      id: '/_authenticated/manage/oratorios/'
      path: '/'
      fullPath: '/manage/oratorios/'
      preLoaderRoute: typeof AuthenticatedManageOratoriosIndexRouteImport
      parentRoute: typeof AuthenticatedManageOratoriosRoute
    }
    '/_authenticated/manage/oratorios/oratorianos': {
      id: '/_authenticated/manage/oratorios/oratorianos'
      path: '/oratorianos'
      fullPath: '/manage/oratorios/oratorianos'
      preLoaderRoute: typeof AuthenticatedManageOratoriosOratorianosRouteImport
      parentRoute: typeof AuthenticatedManageOratoriosRoute
    }
    '/_authenticated/manage/oratorios/$oratorioId': {
      id: '/_authenticated/manage/oratorios/$oratorioId'
      path: '/$oratorioId'
      fullPath: '/manage/oratorios/$oratorioId'
      preLoaderRoute: typeof AuthenticatedManageOratoriosOratorioIdRouteImport
      parentRoute: typeof AuthenticatedManageOratoriosRoute
    }
    '/_authenticated/manage/members/$memberId': {
      id: '/_authenticated/manage/members/$memberId'
      path: '/$memberId'
      fullPath: '/manage/members/$memberId'
      preLoaderRoute: typeof AuthenticatedManageMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedManageMembersRoute
    }
    '/_authenticated/manage/events_/$eventId': {
      id: '/_authenticated/manage/events_/$eventId'
      path: '/manage/events/$eventId'
      fullPath: '/manage/events/$eventId'
      preLoaderRoute: typeof AuthenticatedManageEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manage/oratorios/oratorianos_/$oratorianoId': {
      id: '/_authenticated/manage/oratorios/oratorianos_/$oratorianoId'
      path: '/oratorianos/$oratorianoId'
      fullPath: '/manage/oratorios/oratorianos/$oratorianoId'
      preLoaderRoute: typeof AuthenticatedManageOratoriosOratorianosOratorianoIdRouteImport
      parentRoute: typeof AuthenticatedManageOratoriosRoute
    }
    '/_authenticated/manage/oratorios/$oratorioId_/attendance': {
      id: '/_authenticated/manage/oratorios/$oratorioId_/attendance'
      path: '/$oratorioId/attendance'
      fullPath: '/manage/oratorios/$oratorioId/attendance'
      preLoaderRoute: typeof AuthenticatedManageOratoriosOratorioIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedManageOratoriosRoute
    }
  }
}

interface AuthenticatedManageMembersRouteChildren {
  AuthenticatedManageMembersMemberIdRoute: typeof AuthenticatedManageMembersMemberIdRoute
}

const AuthenticatedManageMembersRouteChildren: AuthenticatedManageMembersRouteChildren =
  {
    AuthenticatedManageMembersMemberIdRoute:
      AuthenticatedManageMembersMemberIdRoute,
  }

const AuthenticatedManageMembersRouteWithChildren =
  AuthenticatedManageMembersRoute._addFileChildren(
    AuthenticatedManageMembersRouteChildren,
  )

interface AuthenticatedManageOratoriosRouteChildren {
  AuthenticatedManageOratoriosOratorioIdRoute: typeof AuthenticatedManageOratoriosOratorioIdRoute
  AuthenticatedManageOratoriosOratorianosRoute: typeof AuthenticatedManageOratoriosOratorianosRoute
  AuthenticatedManageOratoriosIndexRoute: typeof AuthenticatedManageOratoriosIndexRoute
  AuthenticatedManageOratoriosOratorioIdAttendanceRoute: typeof AuthenticatedManageOratoriosOratorioIdAttendanceRoute
  AuthenticatedManageOratoriosOratorianosOratorianoIdRoute: typeof AuthenticatedManageOratoriosOratorianosOratorianoIdRoute
}

const AuthenticatedManageOratoriosRouteChildren: AuthenticatedManageOratoriosRouteChildren =
  {
    AuthenticatedManageOratoriosOratorioIdRoute:
      AuthenticatedManageOratoriosOratorioIdRoute,
    AuthenticatedManageOratoriosOratorianosRoute:
      AuthenticatedManageOratoriosOratorianosRoute,
    AuthenticatedManageOratoriosIndexRoute:
      AuthenticatedManageOratoriosIndexRoute,
    AuthenticatedManageOratoriosOratorioIdAttendanceRoute:
      AuthenticatedManageOratoriosOratorioIdAttendanceRoute,
    AuthenticatedManageOratoriosOratorianosOratorianoIdRoute:
      AuthenticatedManageOratoriosOratorianosOratorianoIdRoute,
  }

const AuthenticatedManageOratoriosRouteWithChildren =
  AuthenticatedManageOratoriosRoute._addFileChildren(
    AuthenticatedManageOratoriosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedManageAccountsRoute: typeof AuthenticatedManageAccountsRoute
  AuthenticatedManageEventsRoute: typeof AuthenticatedManageEventsRoute
  AuthenticatedManageLocationsRoute: typeof AuthenticatedManageLocationsRoute
  AuthenticatedManageMembersRoute: typeof AuthenticatedManageMembersRouteWithChildren
  AuthenticatedManageOratoriosRoute: typeof AuthenticatedManageOratoriosRouteWithChildren
  AuthenticatedManageSolicitationsRoute: typeof AuthenticatedManageSolicitationsRoute
  AuthenticatedManageEventsEventIdRoute: typeof AuthenticatedManageEventsEventIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedManageAccountsRoute: AuthenticatedManageAccountsRoute,
  AuthenticatedManageEventsRoute: AuthenticatedManageEventsRoute,
  AuthenticatedManageLocationsRoute: AuthenticatedManageLocationsRoute,
  AuthenticatedManageMembersRoute: AuthenticatedManageMembersRouteWithChildren,
  AuthenticatedManageOratoriosRoute:
    AuthenticatedManageOratoriosRouteWithChildren,
  AuthenticatedManageSolicitationsRoute: AuthenticatedManageSolicitationsRoute,
  AuthenticatedManageEventsEventIdRoute: AuthenticatedManageEventsEventIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ManageRoute: ManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
